Сервис статистики.
MaximSlepukhin/java-explore-with-me pull request #1
Opened 2024-08-20 20:28 UTC by MaximSlepukhin

2024-08-22 20:01 UTC, mikita95 requested changes
Все сделано очень хорошо :) Оставил лишь незначительные замечания

2024-08-22 20:01 UTC, mikita95 commented on stats/stats-server/src/main/resources/schema.sql
> +ip  VARCHAR(300),
Ip обычно намного более короткая строка, можно задать более строгое ограничение

2024-08-22 22:00 UTC, MaximSlepukhin commented on stats/stats-server/src/main/java/ru/practicum/model/ViewStats.java
> +
Согласен) Исправил.

2024-08-22 22:15 UTC, MaximSlepukhin commented on stats/stats-server/src/main/java/ru/practicum/Util/DateFormatter.java
> +    public static final String pattern = "yyyy-MM-dd HH:mm:ss";
Исправлено.

2024-08-22 22:15 UTC, MaximSlepukhin commented on stats/stats-server/src/main/resources/schema.sql
> +ip  VARCHAR(300),
Исправил.

2024-08-23 18:37 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-08-23 19:12 UTC, merged