Основной сервис.
MaximSlepukhin/java-explore-with-me pull request #2
Opened 2024-09-16 18:34 UTC by MaximSlepukhin

2024-09-29 07:26 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь небольшие замечания

2024-09-29 07:26 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +@Data
Аннотацию data стоит осторожно использовать с сущностями Entity, так как она генерирует toString и hashCode, что может привести к инициализации lazy полей и циклическим вызовам

2024-09-29 07:26 UTC, mikita95 commented on main-service/src/main/resources/db/main-schema.sql
> +initiator_id        BIGINT,
Можно было бы добавить индексы на колонки, по которым часто выполняются запросы, так было бы эффективнее

2024-09-29 09:59 UTC, MaximSlepukhin commented on main-service/src/main/resources/db/main-schema.sql
> +initiator_id        BIGINT,
Добавил.

2024-09-29 09:59 UTC, MaximSlepukhin commented on main-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +@Data
Хороший комментарий.  Исправил.

2024-09-30 10:37 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-09-30 17:49 UTC, merged